SitioWeb_Juegos/SitioWeb_Juegos/Controllers/AdminController.cs
using Datos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
    [Authorize(Roles = "Administrador" )]
    public class AdminController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //// GET: Admin/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/AdminTagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;

namespace SitioWeb_Juegos.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AdminTagsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: AdminTags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: AdminTags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // GET: AdminTags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminTags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tags);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tags);
        }

        // GET: AdminTags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: AdminTags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tags).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tags);
        }

        // GET: AdminTags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: AdminTags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tags tags = db.Tags.Find(id);
            db.Tags.Remove(tags);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/TopController.cs
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
   
    public class TopController : Controller
    {
        private ConsultasUsuarios consultasUsuarios = new ConsultasUsuarios();
        // GET: Top
        public ActionResult _UsuariosTops()
        {
            var model = consultasUsuarios.ObtenerUsuarios();
            return PartialView("_UsuariosTops", model);
        }

        public ActionResult UsuariosTopsWidget()
        {
            var model = consultasUsuarios.ObtenerUsuarios();
            return View(model);
        }

        // GET: Top/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Top/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Top/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Top/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Top/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Top/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Top/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Servicios;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
    public class UsersController : Controller
    {
        public ConsultasUsuarios ConsultasUsuarios = new ConsultasUsuarios();

        // GET: Users
        [Authorize]
        public ActionResult Index(string username)
        {
            var model = ConsultasUsuarios.ObtenerUsuarioPorUsername(username);
            return View(model);
        }

        // GET: Users/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Edit/5
        [Authorize]
        public ActionResult Edit()
        {
            var id = User.Identity.GetUserId();
            var model = ConsultasUsuarios.ObtenerUsuarioPorId(id);         
            if (model == null)
                return RedirectToAction("Index");

            return View(model);        
        }

        // POST: Users/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Usuario model, HttpPostedFileBase Avatar)
        {
            
            try
            {
                if (Avatar != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(model.Avatar)))
                    {
                        System.IO.File.Delete(Server.MapPath(model.Avatar));
                    }
                    WebImage img = new WebImage(Avatar.InputStream);
                    FileInfo fotoinfo = new FileInfo(Avatar.FileName);

                    string nuevafoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 500, false);
                    img.Save("~/Imagenes/ImagenUsuario/" + nuevafoto);
                    model.Avatar = "/Imagenes/ImagenUsuario/" + nuevafoto;

                }
                var id = User.Identity.GetUserId();
                model.Id = id;
                var idGenerado = ConsultasUsuarios.ModificarPerfilUsuario(model);
                return View(model);
            }
            catch
            {
                return View();
            }

        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Footer.cshtml
 <!-- Footer -->
<footer class="footer text-center">
    <div class="container">
        <ul class="list-inline mb-5">
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#">
                    <i class="icon-social-facebook"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#">
                    <i class="icon-social-twitter"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white" href="#">
                    <i class="icon-social-github"></i>
                </a>
            </li>
        </ul>
        <img src="~/Imagenes/juegosennas-logo-min.png" class="mb-0" />
        <p class="text-muted small mb-0">JUEGOSeñas Inc.&copy; JUEGOSeñas&reg; - @DateTime.Now.Year</p>
    </div>
</footer>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JUEGOSeñas - @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/css")
</head>
<body id="page-top">
    @Html.Partial("_NavigationRight")
    @Html.Partial("_NavigationTop")
    @RenderBody()
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</body>
</html>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Administrador - Dashboard</title>



</head>

<body id="page-top">

    @*<button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
          <i class="fas fa-bars"></i>
        </button>*@

    <div id="wrapper">

        <!-- Sidebar -->
        @Html.Partial("_SidebarAdmin")

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Overview</li>
                </ol>

                <!-- Icon Cards-->
                <div class="row">
                    <div class="col-xl-3 col-sm-6 mb-3">
                        <div class="card text-white bg-primary o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-comments"></i>
                                </div>
                                <div class="mr-5">26 New Messages!</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">View Details</span>
                                <span class="float-right">
                                    <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 mb-3">
                        <div class="card text-white bg-warning o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-list"></i>
                                </div>
                                <div class="mr-5">11 New Tasks!</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">View Details</span>
                                <span class="float-right">
                                    <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 mb-3">
                        <div class="card text-white bg-success o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-shopping-cart"></i>
                                </div>
                                <div class="mr-5">123 New Orders!</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">View Details</span>
                                <span class="float-right">
                                    <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 mb-3">
                        <div class="card text-white bg-danger o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-life-ring"></i>
                                </div>
                                <div class="mr-5">13 New Tickets!</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">View Details</span>
                                <span class="float-right">
                                    <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Area Chart Example-->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-chart-area"></i>
                        Area Chart Example
                    </div>
                    <div class="card-body">
                        <canvas id="myAreaChart" width="100%" height="30"></canvas>
                    </div>
                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>

                @RenderBody()
                <!-- DataTables Example -->
                

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_NavigationRight.cshtml
<!-- Navigation -->
<a class="menu-toggle rounded" href="#">
    <i class="fas fa-bars"></i>
</a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a class="js-scroll-trigger" href="#page-top"><b>JUEGO</b>Señas</a>
        </li>


        @*Login y Register*@

        @using Microsoft.AspNet.Identity
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "sidebar-nav" }))
            {
                @Html.AntiForgeryToken()

                <br />
                <br />
                <br />
                <br />
                <li class="sidebar-nav-item">
                    @{
                        if (User.IsInRole("Administrador"))
                        {
                            @Html.ActionLink("Hola " + User.Identity.GetUserName() + "!", "Index", "Admin", routeValues: null, htmlAttributes: new { title = "ManageAdmin" })
                        }
                        else
                        {
                            if (User.IsInRole("Usuario"))
                            {
                                @Html.ActionLink("Hola " + User.Identity.GetUserName() + "!", "Edit", "Users", routeValues: null, htmlAttributes: new { title = "Manage" })
                            }
                            else
                            {
                                if (User.IsInRole("Moderador"))
                                {
                                    @Html.ActionLink("Hola " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                }
                            }
                        }
                    }
                </li>
                <li class="sidebar-nav-item">
                    <a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a>
                </li>

            }
        }
        else
        {
            <hr />
            <li class="sidebar-nav-item">
                @Html.ActionLink("Iniciar sesión", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
            </li>
            <hr />
            <li class="sidebar-nav-item">
                @Html.ActionLink("Registrarse", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
            </li>
            <hr />

        }
    </ul>
</nav>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_NavigationTop.cshtml
@*Barra de navegacion de la parte superior de la página*@
<nav class="navbar navbar-expand-lg navbar-dark">
    <a href="/Home/Index" class="navbar-brand"><b>JUEGO</b>Señas</a>
    <button class="navbar-toggler" type="button" data-target="#navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a href="/Home/Index" class="nav-link">Inicio</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Categorías</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    @{
                        Html.RenderAction("_NavigationCategorias", "Categorias");
                    }
                </div>
            </li>

            <li class="nav-item">
                <a href="/Posts/Index" class="nav-link">Reviews</a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a href="/Posts/Create" class="nav-link">Crear Review</a>
                </li>
                if (User.IsInRole("Administrador"))
                {
                    <li class="nav-item">
                        <a href="/Admin/Index" class="nav-link">Administrar</a>
                    </li>
                }
                else
                {
                    if (User.IsInRole("Usuario"))
                    {
                        <li class="nav-item">
                            <a href="/Users/Edit" class="nav-link">Mi Perfil</a>
                        </li>
                    }
                    else
                    {
                        if (User.IsInRole("Moderador"))
                        {
                            <li class="nav-item">
                                <a href="/Manage/Index" class="nav-link">Mi Perfil</a>
                            </li>
                        }
                    }
                }
            }

            <li >
                <a style="color:white" class="nav-link"> | </a>
            </li>
            <li class="nav-item">
                <a href="/Posts/Search" class="nav-link">Buscar review</a>
            </li>
        </ul>
    </div>
</nav>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_SidebarAdmin.cshtml
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index","AdminUsuarios")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminUsuarios")">
            <i class="fas fa-fw fa-table"></i>
            <span>Usuarios</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminPosts")">
            <i class="fas fa-fw fa-table"></i>
            <span>Posts</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","Comentarios")">
            <i class="fas fa-fw fa-table"></i>
            <span>Comentarios</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","Categorias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Categorias</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminJuegos")">
            <i class="fas fa-fw fa-table"></i>
            <span>Juegos</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminTags")">
            <i class="fas fa-fw fa-table"></i>
            <span>Tags</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","DenunciasPosts")">
            <i class="fas fa-fw fa-table"></i>
            <span>Posts Denunciados</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","DenunciasComentarios")">
            <i class="fas fa-fw fa-table"></i>
            <span>Comentarios Denunciados</span>
        </a>
    </li>

    @*<li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminNoticias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Noticias</span>
        </a>
    </li>*@
</ul>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_SidebarUsuario.cshtml
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Edit","Users")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Perfil</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Posts","Manage")">
            <i class="fas fa-fw fa-table"></i>
            <span>Posts</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("ChangePassword","Manage")">
            <i class="fas fa-fw fa-table"></i>
            <span>Cambiar contraseña</span>
        </a>
    </li>
</ul>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_UsuariosTops.cshtml
@model IEnumerable<Servicios.Usuario>
@{
    ViewBag.Title = "Usuarios Tops";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body id="page-top">
    <div id="wrapper">
        <div id="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">TOP</a>
                    </li>
                    <li class="breadcrumb-item active">10 Usuarios</li>
                </ol>
                <!-- DataTables Example -->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-table"></i>
                        Usuarios
                    </div>



                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Top</th>
                                        <th>Usuario</th>
                                        <th>Puntaje Total</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Top</th>
                                        <th>Usuario</th>
                                        <th>Puntaje Total</th>
                                    </tr>
                                </tfoot>
                                <tbody>

                                    @{
                                        int top = 0;
                                        foreach (var item in Model.Where(x => x.Estado.Descripcion == "Activo").OrderByDescending(x => x.PuntajeTotal).Take(10))
                                        {
                                            top += 1;
                                            <tr>
                                                <td>@top</td>
                                                <td><a href="@Url.Action("Index","Users",new { username = item.UserName})">@item.UserName</a></td>
                                                <td>@item.PuntajeTotal</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer small text-muted">Última actualización: @System.DateTime.Now</div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</body>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Widgets.cshtml
            <!-- Sidebar Widgets Column -->
<div class="col-md-4">
    <!-- Search Widget -->
    @*<div class="card my-4">
        <h5 class="card-header">Búsqueda</h5>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar por...">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="button">Buscar!</button>
                </span>
            </div>
        </div>
    </div>*@

    @*@{ 
//Html.RenderAction("_ListaJuegosBuscador", "AdminJuegos");
    }*@
    <!-- Categorias Widget -->
    @{
        Html.RenderAction("_PartialCategorias", "Categorias");
    }

    <!-- Top Usuarios Widget -->
    @{
        Html.RenderAction("UsuariosTopsWidget", "Top");
    }

</div>