SitioWeb_Juegos/SitioWeb_Juegos/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;
using Microsoft.AspNet.Identity;
using Servicios;

namespace SitioWeb_Juegos.Controllers
{
    public class PostsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();
        private ConsultasEstados consultasEstados = new ConsultasEstados();
        private ConsultasJuegos consultasJuegos = new ConsultasJuegos();
        // GET: Posts
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo");
            ViewBag.SubTitle = "últimas reseñas";
            return View(posts.ToList());
        }

        public ActionResult Search()
        {
            var posts = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo");
            return View(posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            if (posts.Estados.Descripcion != "Activo")
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        
        // GET: Posts/Create
        public ActionResult Create()
        {
            ViewBag.IdJuego = new SelectList(consultasJuegos.ObtenerJuegos(), "Id", "Descripcion");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,Contenido,IdCategoria,IdJuego,FechaPublicacion,Autor,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                posts.FechaPublicacion = DateTime.Now;
                posts.IdEstado = 1;
                posts.Autor = User.Identity.GetUserId();
                db.Posts.Add(posts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdJuego = new SelectList(consultasJuegos.ObtenerJuegos(), "Id", "Descripcion", posts.IdJuego);

            return View(posts);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdEstado = new SelectList(consultasEstados.ObtenerEstados(), "Id", "Descripcion", posts.IdEstado);
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdJuego = new SelectList(consultasJuegos.ObtenerJuegos(), "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Contenido,FechaPublicacion,IdCategoria,Autor,IdJuego,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(posts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdEstado = new SelectList(consultasEstados.ObtenerEstados(), "Id", "Descripcion", posts.IdEstado);
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdJuego = new SelectList(consultasJuegos.ObtenerJuegos(), "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }
        
        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Posts posts = db.Posts.Find(id);
            db.Posts.Remove(posts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult VotarPost(int voto, int IdPost)
        {
            ConsultasPosts consultaspost = new ConsultasPosts();
            var IdAutor = User.Identity.GetUserId();

            Voto model = new Voto();
            model.Usuario = IdAutor;
            model.Cantidad = voto;
            model.IdPost = IdPost;
            var idgenerado = consultaspost.VotarPost(model);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Categorias(int id)
        {
            var model = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo" && x.Juegos.Categorias.Id == id);
            string cat = "";
            foreach (var item in db.Categorias.ToList())
            {
                if (item.Id == id)
                {
                    cat = item.Descripcion;
                }
            }
            ViewBag.SubTitle = cat;
            return View("Index", model.ToList());
        }

        public ActionResult Denunciar()
        {
            ViewBag.Motivo = new SelectList(db.MotivosDenuncia, "Id", "Descripcion");
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Servicios;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
    public class UsersController : Controller
    {
        public ConsultasUsuarios ConsultasUsuarios = new ConsultasUsuarios();

        // GET: Users
        [Authorize]
        public ActionResult Index(string username)
        {
            var model = ConsultasUsuarios.ObtenerUsuarioPorUsername(username);
            return View(model);
        }

        // GET: Users/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Edit/5
        [Authorize]
        public ActionResult Edit()
        {
            var id = User.Identity.GetUserId();
            var model = ConsultasUsuarios.ObtenerUsuarioPorId(id);         
            if (model == null)
                return RedirectToAction("Index");

            return View(model);        
        }

        // POST: Users/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Usuario model, HttpPostedFileBase Avatar)
        {
            
            try
            {
                if (Avatar != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(model.Avatar)))
                    {
                        System.IO.File.Delete(Server.MapPath(model.Avatar));
                    }
                    WebImage img = new WebImage(Avatar.InputStream);
                    FileInfo fotoinfo = new FileInfo(Avatar.FileName);

                    string nuevafoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 500, false);
                    img.Save("~/Imagenes/ImagenUsuario/" + nuevafoto);
                    model.Avatar = "/Imagenes/ImagenUsuario/" + nuevafoto;

                }
                var id = User.Identity.GetUserId();
                model.Id = id;
                var idGenerado = ConsultasUsuarios.ModificarPerfilUsuario(model);
                return View(model);
            }
            catch
            {
                return View();
            }

        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Create.cshtml
@model Datos.Posts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear review</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Contenido, new { @class = "form-control", @cols = 80, @rows = 10 })
                @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdJuego, "Nombre Juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdJuego", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdJuego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Delete.cshtml
@model Datos.Posts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Posts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puntaje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puntaje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Eliminado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eliminado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estados.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estados.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Juegos.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Juegos.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Details.cshtml
@model Datos.Posts
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <h1>@Model.Juegos.Descripcion</h1>
                <!-- Author -->
                
                <p class="lead">
                    @if (Model.AspNetUsers.Avatar == null)
                    {
                        <img class="d-flex mr-3 rounded-circle" src="~/Imagenes/ImagenUsuario/Usuario-Vacio.png" width="125" alt=""> <!-- PONER FOTO DE PERFIL -->
                    }
                    else
                    {
                        <img class="d-flex mr-3 rounded-circle" src="@Model.AspNetUsers.Avatar" width="125" alt=""> <!-- PONER FOTO DE PERFIL -->
                    }
                    por
                    <a href="#">@Model.AspNetUsers.UserName</a>  <!--ESTE HREF DEBE LLEVAR AL PERFIL DEL AUTOR-->
                </p>
                <hr>
                <!-- Date/Time -->
                Fecha de publicación: @Model.FechaPublicacion.ToLongDateString()
                <hr>
                <!-- Preview Image -->
                <img class="img-fluid rounded" src="@Model.Juegos.Imagen" alt="Imagen del juego">
                <hr>
                <!-- Post Content -->
                <p>@Model.Contenido</p>
                <hr />
                <!-- Post Puntajes -->
                <h4>Puntos:@Model.Puntaje</h4>
                @if (User.Identity.IsAuthenticated)
                {
                    if ((User.Identity.GetUserId() != Model.Autor) && (Model.PostDenunciados.Where(x => x.Usuario == User.Identity.GetUserId() && x.IdPost == Model.Id).ToList().Count == 0))
                    {
                        <a class="btn btn-danger" id="btnDenunciarComentario" type="submit" href="@Url.Action("Create","DenunciasPosts",new {IdPost = Model.Id })">Denunciar Post</a>
                    }


                    if ((User.Identity.GetUserId() != Model.Autor) && (Model.Votos.Where(x => x.Usuario == User.Identity.GetUserId() && x.IdPost == Model.Id).ToList().Count == 0))
                    {
                        <!--Contador de Me Gustas-->
                        <div class="qty mt-5">
                            <span class="minus bg-dark">-</span>
                            <input type="number" class="count" id="qty" value="0">
                            <span class="plus bg-dark">+</span>

                            <button type="submit" id="BtnVotar" class="btn btn-primary">Votar</button>
                        </div>

                    }

                    <hr />
                    <!-- Comments Form -->
                    <div class="card my-4">
                        <h5 class="card-header">Deja un comentario:</h5>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <textarea id="Comentario" class="form-control" rows="3"></textarea>
                                </div>
                                <button type="submit" id="BtnComentar" class="btn btn-primary">Comentar</button>
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <h2>¡Debes estar logueado para comentar!</h2>
                    @Html.ActionLink("Iniciar Sesion", "Login", "Account")
                    <hr />
                }

                <!-- Single Comment -->
                @foreach (var item in Model.Comentarios.ToList().Where(x => x.Estados.Descripcion == "Activo"))
                {
                    <div class="media mb-4">
                        @if (item.AspNetUsers.Avatar == null)
                        {
                            <img class="d-flex mr-3 rounded-circle" src="~/Imagenes/ImagenUsuario/Usuario-Vacio.png" width="50" alt=""> <!-- PONER FOTO DE PERFIL -->
                        }
                        else
                        {
                            <img  class="d-flex mr-3 rounded-circle" src="@item.AspNetUsers.Avatar" width="50" alt=""> <!-- PONER FOTO DE PERFIL -->
                        }

                        <div class="media-body">


                            <h5 class="mt-0">@item.AspNetUsers.UserName <small> el @item.FechaPublicacion</small></h5>
                            @item.Contenido
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.Identity.Name == item.AspNetUsers.UserName)
                                {

                                    <button type="submit" id="btnEliminarComentario" data-id="@item.Id" class="btn btn-primary">Eliminar</button>
                                }
                                else
                                {
                                    <a class="btn btn-group" id="btnDenunciarComentario" type="submit" href="@Url.Action("Create","DenunciasComentarios",new { IdComentario = item.Id, IdPost = Model.Id })">Denunciar</a>
                                }
                            }

                        </div>

                    </div>
                    <hr />
                }
            </div>
                @Html.Partial("_Widgets")
            </div>
    </div>

    <!--Scripts del me gusta-->
    @*<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.count').prop('disabled', true);
            $(document).on('click', '.plus', function () {
                $('.count').val(parseInt($('.count').val()) + 1);
                if ($('.count').val() > 5) {
                    $('.count').val(5);
                }
            });
            $(document).on('click', '.minus', function () {
                $('.count').val(parseInt($('.count').val()) - 1);
                if ($('.count').val() < -5) {
                    $('.count').val(-5);
                }
            });
        });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#BtnVotar").click(function () {
            var voto = $("#qty").val();
            if (voto != 0) {
                $.ajax({
                    url: '/Posts/VotarPost/',
                    data: { Voto: voto, IdPost:@Model.Id},
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        alert("Gracias por Votar!");
                        document.location.reload();
                    }
                })
                setTimeout(function () {
                    document.getElementById("BtnVotar").disabled = true;
                    document.getElementById("BtnVotar").innerHTML = "Ya votaste!";
                }, 999999999999999999);
            }
            else {
                alert("Error! El voto no puede ser 0!");
            }
        });
    })
    </script>

    <!--Hace la magia para comentar y ver el comentario creado-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#BtnComentar").click(function () {
                var comment = $("#Comentario").val();
                if (comment.trim() != "") //Se puede ingresar espacios y el comentario se guarda igual, el .trim elimina el espacio en blanco y verifica si es vacio
                {
                    $.ajax({
                        url: '/Comentarios/CrearComentario/',
                        data: { Comentario: comment, IdPost:@Model.Id},
                        type: 'POST',
                        dataType: 'json',
                        success: function (data) {
                            alert("Gracias por Comentar!");
                            document.location.reload();
                        }
                    });
                }
                else {
                    alert("Error! Comentario Vacio");
                }

            });
        })
    </script>

    <!--Hace la magia para borrar comentario creado-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("button[id=btnEliminarComentario]").click(function () {

                if (confirm('Eliminar comentario?')) //Se puede ingresar espacios y el comentario se guarda igual, el .trim elimina el espacio en blanco y verifica si es vacio
                {
                    $.ajax({
                        url: '/Comentarios/EliminarComentario/',
                        data: { IdComentario: $(this).data("id"), IdPost:@Model.Id},
                        type: 'POST',
                        dataType: 'json',
                        success: function (data) {
                            alert("Comentario Eliminado!");
                            document.location.reload();
                        }
                    });
                    
                }

            });
        })
    </script>
</body>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Index.cshtml
@model IEnumerable<Datos.Posts>
@{
    ViewBag.Title = "Reseñas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4">
                    <b>JUEGOS</b>eñas
                    <small> @ViewBag.SubTitle</small>
                </h1>
                <!-- Blog Post -->
                @foreach (var Po in Model.OrderByDescending(x => x.FechaPublicacion))
                {
                    <div class="card mb-4">
                        <img class="card-img-top" src="@Po.Juegos.Imagen" alt="Card image cap">
                        <div class="card-body">
                            <h2 class="card-title">@Po.Juegos.Descripcion </h2>
                            <p class="card-text">@Po.Descripcion</p>
                            <a href="@Url.Action("Details", "Posts", new { id = Po.Id })" class="btn btn-primary">Leer más &rarr;</a>

                        </div>
                        <div class="card-footer text-muted">
                            Fecha publicación: @Po.FechaPublicacion por:
                            <a href="#">@Po.AspNetUsers.UserName</a>
                            <h4>Puntos:@Po.Puntaje</h4>
                        </div>
                    </div>
                }
                <!-- Pagination -->
                <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Antiguas</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Nuevas &rarr;</a>
                    </li>
                </ul>
            </div>
            @Html.Partial("_Widgets")

        </div>
        <!-- /.row -->
    </div>
</body>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Search.cshtml
@model IEnumerable<Datos.Posts>
@{
    ViewBag.Title = "Búsqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body id="page-top">
    <div id="wrapper">
        <div id="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">Buscar</a>
                    </li>
                    <li class="breadcrumb-item active">Reviews</li>
                </ol>
                <!-- DataTables Example -->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-table"></i>
                        Reviews
                    </div>



                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Autor</th>
                                        <th>Título</th>
                                        <th>Descripción</th>
                                        <th>Juego</th>
                                        <th>Imagen</th>
                                        <th>Categoría</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Autor</th>
                                        <th>Título</th>
                                        <th>Descripción</th>
                                        <th>Juego</th>
                                        <th>Imagen</th>
                                        <th>Categoría</th>
                                    </tr>
                                </tfoot>
                                <tbody>

                                    @{
                                        foreach (var item in Model.OrderByDescending(x => x.FechaPublicacion))
                                        {
                                    <tr>
                                        <td><a href="@Url.Action("Index","Users",new { username = item.AspNetUsers.UserName})">@item.AspNetUsers.UserName</a></td>
                                        <td><a href="@Url.Action("Details", "Posts", new { id = item.Id })">@item.Titulo</a></td>
                                        <td>@item.Descripcion</td>
                                        <td>@item.Juegos.Descripcion</td>
                                        <td><img width="175" src="@item.Juegos.Imagen" /></td>
                                        <td>@item.Juegos.Categorias.Descripcion</td>
                                    </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer small text-muted">Última actualización: @System.DateTime.Now</div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</body>